config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness:true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(params_bookmark)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    # @list = List.find(@bookmark.list_id)
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def params_bookmark
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  private

  def params_list
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmark a movie</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :comment %>
<%= f.association :movie %>
<%= f.submit %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-terciary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">WatchList</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "My lists", lists_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New list", new_list_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba);">
  <div class="container">
    <h1 class="pb-5">Save any kind of movies</h1>
  </div>
</div>

<div class="container mb-5">

  <div class="d-flex justify-content-center align-items-center p-3">
    <%= link_to "Create a movie list", new_list_path(@movies), class:"btn btn-primary" %>
   </div>

  <div class="container row justify-content-around gap-2">
    <% @lists.each do |list| %>
      <div class="card col-3">
        <% if list.photo.key? %>
          <%= cl_image_tag list.photo.key, crop: :fill %>
        <% else %>
          <%= image_tag "default-list-image.png", alt: "Le Wagon" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= list.name %></h5>
          <p><%= link_to "More info", list_path(list), class:"btn btn-primary" %></p>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/lists/new.html.erb
<h1>Create a new List</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<% if @list.photo.key? %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key %>);">
<% else %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "default-list-image.png" %>);">
<% end %>
    <div class="container">
      <h1 class="pb-5"><%= @list.name %></h1>
    </div>
  </div>

<div class="container mb-5">

  <div class="d-flex justify-content-center align-items-center p-3">
    <h1><%= link_to "Bookmark a movie", new_list_bookmark_path(@list), class:"btn btn-primary" %></h1>
  </div>

  <div class="container row justify-content-around gap-2">
    <% @bookmarks.each do |bookmark| %>
    <% if bookmark.list = @list %>
      <div class="card col-3">
        <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="<%= bookmark.movie.title %>">
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <h4 class="card-title"><%= bookmark.movie.title %></h4>
            <p><span style="color: #FFC300;"><i class="fa-solid fa-star pe-1"></i></span><%= bookmark.movie.rating %></p>
          </div>
          <p class="card-text"><%= bookmark.movie.overview %></p>
          <p class="card-text border-top border-info pt-2"><i class="fa-solid fa-quote-left"></i> <%= bookmark.comment %></p>
          <div class="d-flex justify-content-end">
            <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>

</div>